### ISSUE TITLE
A website domain changes

### ISSUE THREAD

**Issue by No0ne003** [isabelroses/catppuccin-webring#41]
the website https://lighttigerxiv.vercel.app/connect in the webring doesn't work and that make it block the webring

**Comment by isabelroses** [comment]
@lighttigerXIV could you help us out here

**Comment by lighttigerXIV** [comment]
> @lighttigerXIV could you help us out here

You can remove it from the webring I don't mind. I changed domain and refactored the website and forgot to make the webring part XD
